server:
  port: 8088
  tomcat:
    uri-encoding:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xwglxt?useUnicode=true&amp;characterEncoding=UTF8?autoReconnect=true
    username: root
    password: 17200

mybatis:
  type-aliases-package: cn.common.pojo
  mapper-locations: classpath:mapper/*.xml

